### ISSUE TITLE
Is there a chance to apply it to Swagger like TypeBox?

### ISSUE THREAD

**Issue by vreallyla** [Savolus/elysia-with-zod#1]
any changes?

**Comment by Savolus** [comment]
Hi @vreallyla 
I have just merged swagger for zod schemas to the main branch. Documentation is available on `/swagger` endpoint.
Unfortunately I was able to add the schemas to the documentation but wasn't able to link these schemas to the endpoints.

**Comment by vreallyla** [comment]
Hi @Savolus 
Thanks for the quick response. I really appreciate your help 😄. I tried it locally and the server is working, but unfortunately, when I tried to set the body type, the result of the body does not appear in `/swagger`. Here is the evidence:
<img width="1113" alt="image" src="https://github.com/user-attachments/assets/7ee51f67-9421-4be2-9f32-434a311b0a32">
<img width="559" alt="image" src="https://github.com/user-attachments/assets/bb300cc6-6658-47e7-9ac2-77b502b4e748">

**my expected:**
<img width="1179" alt="image" src="https://github.com/user-attachments/assets/51b12771-9e37-427f-8991-841bbb4d923b">

If I may suggest, it would be great if this project became a package. it's great repo

Thanks

> Hi @vreallyla I have just merged swagger for zod schemas to the main branch. Documentation is available on `/swagger` endpoint. Unfortunately I was able to add the schemas to the documentation but wasn't able to link these schemas to the endpoints.

**Comment by Savolus** [comment]
The registering for the schemas is done not in place. You are required to call registry.registerParameters.
However, you are right, it doesn't set the body as you mentioned. Currently I don't have the solution for this. Might check it after the main work)

**Comment by vreallyla** [comment]
Thank you for the insight. I understand that the schemas need to be registered using `registry.registerParameters` and that it requires more effort. I appreciate your acknowledgment regarding the body issues. I look forward to any updates you might have after your main work

Thanks again and have a good day!

**Comment by Savolus** [comment]
Hi @vreallyla 
Here is an updated version: please check the attachment
<img width="1510" alt="Screenshot 2024-08-30 at 19 36 19" src="https://github.com/user-attachments/assets/8053143f-6096-4ec1-a1c1-8d8a86a32bff">
